#!/bin/sh

run() {
  if ! pgrep -f "$1" ;
  then
    "$@"&
  fi
}


picom -b --config ~/.config/picom/picom.conf
wal -R
rclone --vfs-cache-mode writes mount "Onedrive": ~/Onedrive
run xsettingsd
run nm-applet
run light-locker --no-lock-on-lid
run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
